# Generated by Django 2.2.1 on 2019-05-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='registration_number',
        ),
    ]
