# Generated by Django 2.2.1 on 2019-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
